title: Lake Proa
description: >- # this means to ignore newlines until "baseurl:"
  Building and sailing Proa on lakes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://augustasvol.github.io/lakeproa" # the base hostname & protocol for your site
theme: jekyll-theme-minimal # choose a Jekyll theme, e.g., minima
